export default themeColors = {
  light: {
    textColor: "black",
    background: "white",
    oppositeBkg: "#15202b",
    border: "black",
    barStyle: "dark-content",
    accent: "#eee8f5",
    searchBarPlaceholder: "grey",
    grey: "grey",
    selectorActive: "white",
    selectorInactive: "black",
  },
  dark: {
    textColor: "white",
    background: "#15202b",
    oppositeBkg: "white",
    border: "grey",
    barStyle: "light-content",
    accent: "#8899ac",
    searchBarPlaceholder: "lightgrey",
    grey: "grey",
    selectorActive: "white",
    selectorInactive: "white",
  },
};
